# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.provider "virtualbox" do |vb|
     vb.gui = false
     vb.memory = "2048"
     vb.cpus = "2" 
  end
  
  config.vm.define "k8smaster" do |master|
    master.vm.network "public_network", bridge: "enx00e04c7c3ee3", ip: "192.168.15.70"
    master.vm.provider "virtualbox" do |vb|
        vb.memory = "4096"
        vb.cpus = "2"
    end
    master.vm.synced_folder "./docker", "/tmp/docker"
    master.vm.provision "shell", inline: <<-SHELL
      apt-get update && apt-get install -y curl
      hostname elliot-k8s-master
      curl -fsSL https://get.docker.com | bash
      sudo cp -f /tmp/docker/daemon.json /etc/docker/
      sudo mkdir -p /etc/systemd/system/docker.service.d
      sudo systemctl daemon-reload
      sudo systemctl restart docker
      sudo apt-get update && sudo apt-get install -y apt-transport-https gnupg2
      curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
      sudo echo "deb http://apt.kubernetes.io/ kubernetes-xenial main" > /etc/apt/sources.list.d/kubernetes.list
      sudo apt-get update
      sudo apt-get install -y kubelet kubeadm kubectl
      export KUBECONFIG=/etc/kubernetes/kubelet.conf
      sudo swapoff -a
      sudo kubeadm config images pull
      sudo kubeadm init --apiserver-advertise-address 192.168.15.70 --apiserver-cert-extra-sans=10.0.2.15,0.0.0.0
      mkdir -p $HOME/.kube
      sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
      sudo chown $(id -u):$(id -g) $HOME/.kube/config
      sudo modprobe br_netfilter ip_vs_rr ip_vs_wrr ip_vs_sh nf_conntrack_ipv4 ip_vs
      kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"
    SHELL
    master.vm.synced_folder "./config", "/configs"
    master.vm.synced_folder ".", "/vagrant", disabled: "true"
  end
  config.vm.define "k8sworker1" do |worker1|
    worker1.vm.network "public_network", bridge: "enx00e04c7c3ee3",  ip: "192.168.15.71"
    worker1.vm.synced_folder "./docker", "/tmp/docker"
    worker1.vm.provision "shell", inline: <<-SHELL
      apt-get update && apt-get install -y curl
      hostname elliot-worker-01
      curl -fsSL https://get.docker.com | bash
      sudo cp -f /tmp/docker/daemon.json /etc/docker/
      sudo mkdir -p /etc/systemd/system/docker.service.d
      sudo systemctl daemon-reload
      sudo systemctl restart docker
      sudo apt-get update && sudo apt-get install -y apt-transport-https gnupg2
      curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
      sudo echo "deb http://apt.kubernetes.io/ kubernetes-xenial main" > /etc/apt/sources.list.d/kubernetes.list
      sudo apt-get update
      sudo apt-get install -y kubelet kubeadm kubectl
      export KUBECONFIG=/etc/kubernetes/kubelet.conf
      sudo swapoff -a
    SHELL
    worker1.vm.synced_folder "./config", "/configs"
    worker1.vm.synced_folder ".", "/vagrant", disabled: "true"
  end
  config.vm.define "k8sworker2" do |worker2|
    worker2.vm.network "public_network", bridge: "enx00e04c7c3ee3", ip: "192.168.15.72"
    worker2.vm.synced_folder "./docker", "/tmp/docker"  
    worker2.vm.provision "shell", inline: <<-SHELL
      apt-get update && apt-get install -y curl
      hostname elliot-worker-02
      curl -fsSL https://get.docker.com | bash
      sudo cp -f /tmp/docker/daemon.json /etc/docker/
      sudo mkdir -p /etc/systemd/system/docker.service.d
      sudo systemctl daemon-reload
      sudo systemctl restart docker
      sudo apt-get update && sudo apt-get install -y apt-transport-https gnupg2
      curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
      sudo echo "deb http://apt.kubernetes.io/ kubernetes-xenial main" > /etc/apt/sources.list.d/kubernetes.list
      sudo apt-get update
      sudo apt-get install -y kubelet kubeadm kubectl
      export KUBECONFIG=/etc/kubernetes/kubelet.conf
      sudo swapoff -a
    SHELL
    worker2.vm.synced_folder "./config", "/configs"
    worker2.vm.synced_folder ".", "/vagrant", disabled: "true"
  end
end
