# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.provider "virtualbox" do |vb|
     vb.gui = false
     vb.memory = "2048"
     vb.cpus = "2" 
  end
  
  config.vm.define "k8smaster1" do |master1|
    master1.vm.network "public_network", bridge: "enx00e04c7c3ee3", ip: "192.168.15.80"
    master1.vm.synced_folder "./docker", "/tmp/docker"
    master1.vm.provider "virtualbox" do |vb|
        vb.memory = "4096"
        vb.cpus = "2"
    end
    master1.vm.provision "shell", inline: <<-SHELL
      export DEBIAN_FRONTEND=noninteractive
      apt-get update && apt-get install -y curl
      hostname elliot-k8s-master1
      echo "127.0.0.1 elliot-k8s-master1" >> /etc/hosts
      curl -fsSL https://get.docker.com | bash
      sudo cp -f /tmp/docker/daemon.json /etc/docker/
      sudo mkdir -p /etc/systemd/system/docker.service.d
      sudo systemctl daemon-reload
      sudo systemctl restart docker
      sudo apt-get update && sudo apt-get install -y apt-transport-https gnupg2
      curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
      sudo echo "deb http://apt.kubernetes.io/ kubernetes-xenial main" > /etc/apt/sources.list.d/kubernetes.list
      sudo apt-get update
      sudo apt-get install -y kubelet kubeadm kubectl
      export KUBECONFIG=/etc/kubernetes/kubelet.conf
      sudo cp -f /tmp/docker/k8s.conf /etc/modules-load.d/
      sudo swapoff -a
      sudo kubeadm config images pull
    SHELL
    master1.vm.synced_folder "./config", "/configs"
    master1.vm.synced_folder ".", "/vagrant", disabled: "true"
  end
  config.vm.define "k8smaster2" do |master2|
    master2.vm.network "public_network", bridge: "enx00e04c7c3ee3", ip: "192.168.15.81"
    master2.vm.synced_folder "./docker", "/tmp/docker"
    master2.vm.provider "virtualbox" do |vb|
        vb.memory = "4096"
        vb.cpus = "2"
    end
    master2.vm.provision "shell", inline: <<-SHELL
      export DEBIAN_FRONTEND=noninteractive
      apt-get update && apt-get install -y curl
      hostname elliot-k8s-master2
      echo "127.0.0.1 elliot-k8s-master2" >> /etc/hosts
      curl -fsSL https://get.docker.com | bash
      sudo cp -f /tmp/docker/daemon.json /etc/docker/
      sudo mkdir -p /etc/systemd/system/docker.service.d
      sudo systemctl daemon-reload
      sudo systemctl restart docker
      sudo apt-get update && sudo apt-get install -y apt-transport-https gnupg2
      curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
      sudo echo "deb http://apt.kubernetes.io/ kubernetes-xenial main" > /etc/apt/sources.list.d/kubernetes.list
      sudo apt-get update
      sudo apt-get install -y kubelet kubeadm kubectl
      export KUBECONFIG=/etc/kubernetes/kubelet.conf
      sudo cp -f /tmp/docker/k8s.conf /etc/modules-load.d/
      sudo swapoff -a
      sudo kubeadm config images pull
    SHELL
    master2.vm.synced_folder "./config", "/configs"
    master2.vm.synced_folder ".", "/vagrant", disabled: "true"
  end
  config.vm.define "k8smaster3" do |master3|
    master3.vm.network "public_network", bridge: "enx00e04c7c3ee3", ip: "192.168.15.82"
    master3.vm.synced_folder "./docker", "/tmp/docker"
    master3.vm.provider "virtualbox" do |vb|
        vb.memory = "4096"
        vb.cpus = "2"
    end
    master3.vm.provision "shell", inline: <<-SHELL
      export DEBIAN_FRONTEND=noninteractive
      apt-get update && apt-get install -y curl
      hostname elliot-k8s-master3
      echo "127.0.0.1 elliot-k8s-master3" >> /etc/hosts
      curl -fsSL https://get.docker.com | bash
      sudo cp -f /tmp/docker/daemon.json /etc/docker/
      sudo mkdir -p /etc/systemd/system/docker.service.d
      sudo systemctl daemon-reload
      sudo systemctl restart docker
      sudo apt-get update && sudo apt-get install -y apt-transport-https gnupg2
      curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
      sudo echo "deb http://apt.kubernetes.io/ kubernetes-xenial main" > /etc/apt/sources.list.d/kubernetes.list
      sudo apt-get update
      sudo apt-get install -y kubelet kubeadm kubectl
      export KUBECONFIG=/etc/kubernetes/kubelet.conf
      sudo cp -f /tmp/docker/k8s.conf /etc/modules-load.d/
      sudo swapoff -a
      sudo kubeadm config images pull
    SHELL
    master3.vm.synced_folder "./config", "/configs"
    master3.vm.synced_folder ".", "/vagrant", disabled: "true"
  end
  config.vm.define "k8sworker1" do |worker1|
    worker1.vm.network "public_network", bridge: "enx00e04c7c3ee3",  ip: "192.168.15.83"
    worker1.vm.synced_folder "./docker", "/tmp/docker"
    worker1.vm.provision "shell", inline: <<-SHELL
      export DEBIAN_FRONTEND=noninteractive
      apt-get update && apt-get install -y curl
      hostname elliot-worker-01
      curl -fsSL https://get.docker.com | bash
      sudo cp -f /tmp/docker/daemon.json /etc/docker/
      sudo cp -f /tmp/docker/k8s.conf /etc/modules-load.d/
      sudo mkdir -p /etc/systemd/system/docker.service.d
      sudo systemctl daemon-reload
      sudo systemctl restart docker
      sudo apt-get update && sudo apt-get install -y apt-transport-https gnupg2
      curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
      sudo echo "deb http://apt.kubernetes.io/ kubernetes-xenial main" > /etc/apt/sources.list.d/kubernetes.list
      sudo apt-get update
      sudo apt-get install -y kubelet kubeadm kubectl
      export KUBECONFIG=/etc/kubernetes/kubelet.conf
      sudo swapoff -a
    SHELL
    worker1.vm.synced_folder "./config", "/configs"
    worker1.vm.synced_folder ".", "/vagrant", disabled: "true"
  end
  config.vm.define "k8sworker2" do |worker2|
    worker2.vm.network "public_network", bridge: "enx00e04c7c3ee3", ip: "192.168.15.84"
    worker2.vm.synced_folder "./docker", "/tmp/docker"  
    worker2.vm.provision "shell", inline: <<-SHELL
      export DEBIAN_FRONTEND=noninteractive
      apt-get update && apt-get install -y curl
      hostname elliot-worker-02
      curl -fsSL https://get.docker.com | bash
      sudo cp -f /tmp/docker/daemon.json /etc/docker/
      sudo cp -f /tmp/docker/k8s.conf /etc/modules-load.d/
      sudo mkdir -p /etc/systemd/system/docker.service.d
      sudo systemctl daemon-reload
      sudo systemctl restart docker
      sudo apt-get update && sudo apt-get install -y apt-transport-https gnupg2
      curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
      sudo echo "deb http://apt.kubernetes.io/ kubernetes-xenial main" > /etc/apt/sources.list.d/kubernetes.list
      sudo apt-get update
      sudo apt-get install -y kubelet kubeadm kubectl
      export KUBECONFIG=/etc/kubernetes/kubelet.conf
      sudo swapoff -a
    SHELL
    worker2.vm.synced_folder "./config", "/configs"
    worker2.vm.synced_folder ".", "/vagrant", disabled: "true"
  end
  config.vm.define "k8sworker3" do |worker3|
    worker3.vm.network "public_network", bridge: "enx00e04c7c3ee3", ip: "192.168.15.85"
    worker3.vm.synced_folder "./docker", "/tmp/docker"
    worker3.vm.provision "shell", inline: <<-SHELL
      export DEBIAN_FRONTEND=noninteractive
      apt-get update && apt-get install -y curl
      hostname elliot-worker-02
      curl -fsSL https://get.docker.com | bash
      sudo cp -f /tmp/docker/daemon.json /etc/docker/
      sudo cp -f /tmp/docker/k8s.conf /etc/modules-load.d/
      sudo mkdir -p /etc/systemd/system/docker.service.d
      sudo systemctl daemon-reload
      sudo systemctl restart docker
      sudo apt-get update && sudo apt-get install -y apt-transport-https gnupg2
      curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
      sudo echo "deb http://apt.kubernetes.io/ kubernetes-xenial main" > /etc/apt/sources.list.d/kubernetes.list
      sudo apt-get update
      sudo apt-get install -y kubelet kubeadm kubectl
      export KUBECONFIG=/etc/kubernetes/kubelet.conf
      sudo swapoff -a
    SHELL
    worker3.vm.synced_folder "./config", "/configs"
    worker3.vm.synced_folder ".", "/vagrant", disabled: "true"
  end
  config.vm.define "haproxy1" do |haproxy1|
    haproxy1.vm.network "public_network", bridge: "enx00e04c7c3ee3", ip: "192.168.15.150"
    haproxy1.vm.synced_folder "./docker", "/tmp/docker"
    haproxy1.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
        vb.cpus = "1"
    end
    haproxy1.vm.provision "shell", inline: <<-SHELL
      export DEBIAN_FRONTEND=noninteractive
      apt-get update && apt-get install -y curl
      hostname elliot-haproxy-01
      apt-get install -y haproxy
    SHELL
    haproxy1.vm.synced_folder "./config", "/configs"
    haproxy.vm.synced_folder ".", "/vagrant", disabled: "true"
  end
end
